### ISSUE TITLE
ディレクトリ構成の構築

### ISSUE THREAD

**Issue by m5151128** [m5151128/flaskr#3]
113f577 時点ではmanage.pyの1ファイルでしか動作していない。
(とりあえず動くのを作ったため)

いい感じにディレクトリ構成したい

**Comment by m5151128** [comment]
考案:

基本は[プロジェクトのレイアウト](https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/tutorial/layout.html) に
models & migrations を追加かな？

### modelsディレクトリ

* model関連

### migrationsディレクトリ

* flask_migrateのmigrations

**Comment by m5151128** [comment]
メモ：

modelsの中で
```python
from manage import db
```
だとエラーになる。理由はわからん。。。
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/var/www/flaskr/manage.py", line 4, in <module>
    from app.models import Post, User
  File "/var/www/flaskr/app/models/__init__.py", line 1, in <module>
    from .post import Post
  File "/var/www/flaskr/app/models/post.py", line 1, in <module>
    from manage import db
ImportError: cannot import name 'db' from partially initialized module 'manage' (most likely due to a circular import) (/var/www/flaskr/manage.py)
```

circular import (循環読み込み？) なんてしてないよ。。。？
manage でも import db してたりはしてない。

しょうがなく、application.pyを新規作成しdbを定義してなら行ける。
```python
from manage import db
```
よくわからん。。。
むしろこれの方が import db が増えちゃってるけれど。。。？
